export default function Head() {
  return (
    <>
      <title>NeuralFin</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* want to input the neuralfin-logo-beta icon from the neuralfin-logo folder */}
      <link rel="icon" href="/neuralfin-logo-beta-ico.ico" />
    </>
  )

  }
