[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-package-lock"]

[phases.build]
cmds = ["npm run build || true"]

[start]
cmd = "npm start"

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 