[phases.setup]
nixPkgs = ["nodejs@20", "libc6-compat"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]
dependsOn = ["setup"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm run start" 