[build]
builder = "nixpacks"
buildCommand = "npm ci --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
installCommand = "npm ci --legacy-peer-deps" 