[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
nixPackages = ["nodejs", "npm"]

[nixpacks.env]
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 