[build]
nixpacks = true
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.json"
buildCommand = "npm run build || true"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300 